DELETE FROM directors;
DELETE FROM films;
DELETE FROM users;
DELETE FROM film_likes;
DELETE FROM film_genres;
DELETE FROM film_directors;

ALTER TABLE directors ALTER COLUMN id RESTART WITH 1;
ALTER TABLE films ALTER COLUMN id RESTART WITH 1;
ALTER TABLE users ALTER COLUMN id RESTART WITH 1;
ALTER TABLE film_likes ALTER COLUMN id RESTART WITH 1;
ALTER TABLE film_genres ALTER COLUMN id RESTART WITH 1;
ALTER TABLE film_directors ALTER COLUMN id RESTART WITH 1;